Repository alexander-l-stone/RogueSpace, pull requests merged in 2021-08, with the labels that each got.

#22 Animated entities
  source/area/area.py
  source/cloud/cloud.py
  source/entity/entity.py
  source/ship/ship.py
  source/system/star.py
  source/system/system.py
  test/test_moon.py
  test/test_newtonian_entity.py
Labels: enhancement

#40 Grammar functions and tag overhaul
  grammar/function_library_parser.py
  grammar/grammar.py
  grammar/rule.py
  grammar/shitty_grammar.json
  grammar/test/test_grammar.py
  grammar/test/test_rule.py
  grammar/universal_function_library.py
  test/conftest.py
  test/test_galaxy.py
  test/test_system.py
Labels: Developer Experience, Procedural Generation

#45 [grammar-loop] Removed trampoline from grammar.py.
  grammar/grammar.py
Labels: Developer Experience, Procedural Generation

#41 Introduces Basic Debug Mode
  source/action/action.py
  source/draw/area/__init__.py
  source/draw/area/area.py
  source/draw/entity/__init__.py
  source/draw/entity/entity.py
  source/draw/entity/newtonian_entity.py
  source/engine/eventengine.py
  source/engine/renderengine.py
  source/galaxy/galaxy.py
  source/galaxy_generator/galaxy_generator.py
  source/game.py
  source/handlers/input_handler.py
  source/handlers/menu_handler.py
  source/menu/__init__.py
  source/menu/menu.py
  source/planet/__init__.py
  source/player/player.py
  source/ring/__init__.py
  source/ship/ship.py
  source/stellar_objects/__init__.py
  source/stellar_objects/belt.py
  source/stellar_objects/cloud.py
  source/stellar_objects/moon.py
  source/stellar_objects/planet.py
  source/stellar_objects/ring.py
  source/stellar_objects/star.py
  source/system/system.py
  source/ui/game_window.py
  source/ui/menu/__init__.py
  source/ui/menu/generate_menu.py
  source/ui/menu/menu.py
  source/ui/menu/menu_item.py
  source/ui/ui_bar.py
  source/ui/ui_message.py
  source/ui/ui_panel.py
  test/conftest.py
  test/test_area.py
  test/test_collisions.py
  test/test_entity.py
  test/test_menu.py
  test/test_moon.py
  test/test_newtonian_entity.py
  test/test_planet.py
  test/test_system.py
Labels: Developer Experience

#46 Grammar
  grammar/__init__.py
  grammar/function_library_parser.py
  grammar/grammar.py
  grammar/rule.py
  grammar/shitty_grammar.json
  grammar/test/__init__.py
  grammar/test/test_grammar.py
  grammar/test/test_rule.py
  grammar/universal_function_library.py
  resources/grammars/system_grammar.json
  source/galaxy_generator/galaxy_generator.py
  source/stellar_objects/planet.py
  source/system/system.py
  test/conftest.py
  test/test_galaxy.py
  test/test_system.py
Labels: Developer Experience, Procedural Generation

#64 Tileset
  source/action/resolution_functions.py
  source/draw/area/tilesetarea.py
  source/engine/eventengine.py
  source/engine/renderengine.py
  source/game.py
  source/planet_space/__init__.py
  source/planet_space/planet_space.py
  source/ship/ship_components/__init__.py
  source/tileset/__init__.py
  source/tileset/tileset.py
  source/ui/__init__.py
  source/ui/menu/generate_menu.py
  test/conftest.py
  test/test_tileset.py
Labels: Developer Experience, Procedural Generation
